[my_docker_hosts]
VM2 ansible_host=192.168.8.119 ansible_user=sysadmin
VM3 ansible_host=192.168.8.120 ansible_user=sysadmin
VM4 ansible_host=192.168.8.121 ansible_user=sysadmin
VM5 ansible_host=192.168.8.122 ansible_user=sysadmin

[backup_targets]
VM5 ansible_host=192.168.8.122 ansible_user=sysadmin

[all:vars]
ansible_user=sysadmin
ansible_ssh_pass=linux
ansible_become=true
ansible_become_method=sudo
ansible_become_password=linux
